// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvPc4nBqa7fQIa_G0KYi4tuqRiN8suRCQ',
    appId: '1:866864208741:web:54279b436621ecfb671f8c',
    messagingSenderId: '866864208741',
    projectId: 'crud-b1c70',
    authDomain: 'crud-b1c70.firebaseapp.com',
    storageBucket: 'crud-b1c70.appspot.com',
    measurementId: 'G-RC5ERZH7M2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBftse4r0a6vsaEiGxxN4UYWZ0NvhTHVvo',
    appId: '1:866864208741:android:29519805c6c32277671f8c',
    messagingSenderId: '866864208741',
    projectId: 'crud-b1c70',
    storageBucket: 'crud-b1c70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKTSp7qfUsp52jbmTPzURnaCarQvKV-xk',
    appId: '1:866864208741:ios:966c9455cc2f5e02671f8c',
    messagingSenderId: '866864208741',
    projectId: 'crud-b1c70',
    storageBucket: 'crud-b1c70.appspot.com',
    iosBundleId: 'com.example.crudDanielmorales',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKTSp7qfUsp52jbmTPzURnaCarQvKV-xk',
    appId: '1:866864208741:ios:44976cc91d48984c671f8c',
    messagingSenderId: '866864208741',
    projectId: 'crud-b1c70',
    storageBucket: 'crud-b1c70.appspot.com',
    iosBundleId: 'com.example.crudDanielmorales.RunnerTests',
  );
}
